imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ["api"]
    handlers:
        main:
            type:  rotating_file
            max_files: 5
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: ["!api"]
        api:
            type:  rotating_file
            max_files: 5
            path:   "%kernel.logs_dir%/api.%kernel.environment%.log"
            level:  debug
            channels: [api]
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

#assetic:
#    use_controller: "%use_assetic_controller%"