imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        handler_id: ~
    profiler:
        collect: false
    form:
        csrf_protection:
            enabled:              false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

csa_guzzle:
    cache:
        enable: true