imports:
    - { resource: parameters.yml }
    - { resource: parameters_env.yml }
    - { resource: version.yml }
    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ ]
#    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
#        #closure:
#        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        #yui_css:
#        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    auth_mode:  "%mailer_auth_mode%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    port: "%mailer_port%"
    logging:  "%kernel.debug%"
#    spool:     { type: memory }
#    delivery_address: some-address@stonje.com

#forms_main:
#    api:
#        url: %main.api.url%
#        username: %main.api.username%
#        password: %main.api.password%
#        verify_ssl: %main.api.verify_ssl%

csa_guzzle:
    profiler: %kernel.debug%
