<?php

namespace CoreBundle\Repository;

/**
 * BlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DspBlocRepository extends \Doctrine\ORM\EntityRepository
{
}
