<?php

namespace CoreBundle\Repository;

/**
 * DspPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DspPageRepository extends \Doctrine\ORM\EntityRepository
{
}
