<?php

namespace CoreBundle\Repository;

/**
 * DspRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DspRepository extends \Doctrine\ORM\EntityRepository
{
}
