<?php

namespace CoreBundle\Repository;

/**
 * PatientHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientHistoriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
