<?php

namespace CoreBundle\Repository;

/**
 * PatientConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientConsultationRepository extends \Doctrine\ORM\EntityRepository
{
}
