<?php

namespace CoreBundle\Repository;

/**
 * VariableListeChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableListeChoixRepository extends \Doctrine\ORM\EntityRepository
{
}
