<?php

namespace CoreBundle\Repository;

/**
 * VariableTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
