<?php

namespace CoreBundle\Repository;

/**
 * VariableNomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableNomRepository extends \Doctrine\ORM\EntityRepository
{
}
