parameters:
    forms_client.menu_routing:
        actualites:
            menu_item: forms_client_content_news_summary
            path: /actualites
        contact:
            menu_item: forms_client_contact
            path: /contact
        connexion:
            menu_item: forms_client_login
            path: /connexion