parameters:
    forms_client.menu_routing:
        actualites:
            menu_item: forms_client_content_news_summary
            path: /actualites
            submenu:
                actualites:
                    menu_item: forms_client_content_news_summary
                    path: /actualites
