# -- Homepage

forms_client_main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Home:index }

forms_client_main_contact_form:
    path:     /contact/form
    defaults: { _controller: MainBundle:Contact:form }
    requirements:
        method: GET|POST

forms_client_main_faq:
    path:       /faq
    defaults:   { _controller: MainBundle:Faq:index }
    requirements:
        method: GET
